### ISSUE TITLE
How to listen on a port other than 3306 ?

### ISSUE THREAD

**Issue by wuyudian1** [bitnami/bitnami-docker-mysql#100]
How to listen on a port other than 3306 ?

I changed the port number from 3306 to 3310 in `mysqld.cnf`,
and I mounted it to `/opt/bitnami/mysql/conf/my.cnf`

the content of my `mysqld.cnf` is:
```
[mysqladmin]
user=

[mysqld]
skip-name-resolve
explicit_defaults_for_timestamp
basedir=/opt/bitnami/mysql
port=3310
tmpdir=/opt/bitnami/mysql/tmp
socket=/opt/bitnami/mysql/tmp/mysql.sock
pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
max_allowed_packet=16M
bind-address=127.0.0.1
log-error=/bitnami/mysql/data/error.log
character-set-server=UTF8
collation-server=utf8_general_ci
plugin_dir=/opt/bitnami/mysql/plugin

[client]
port=3310
socket=/opt/bitnami/mysql/tmp/mysql.sock
default-character-set=UTF8
plugin_dir=/opt/bitnami/mysql/plugin

[manager]
port=3310
socket=/opt/bitnami/mysql/tmp/mysql.sock
pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
```
But the container can not start, because there's another container listenning on 3306.

**Comment by dani8art** [comment]
Hi @wuyudian1 ,

> But the container can not start, because there's another container listenning on 3306.

If the error is that, it seems like you have another 'old' container running and attached to this port, you could see your running container by running this command:

```bash
$ docker ps
```
BTW, the best approach to change the default port for `bitnami-docker-mysql` would be using the proper environment variable like adding it to the docker command, see more env vars [here](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql-env.sh#L34):

```bash
$ docker run \
    -e ALLOW_EMPTY_PASSWORD=yes \
    -e MYSQL_PORT_NUMBER=3310 \
    -p 3310:3310
    bitnami/mysql:latest
```

**Comment by wuyudian1** [comment]
@dani8art  Thanks for your help.
