### ISSUE TITLE
MYSQL_ROOT_USER and custom files docker-entrypoint-initdb.d not compatible

### ISSUE THREAD

**Issue by icrc-fdeniger** [bitnami/bitnami-docker-mysql#104]
**Description**

If the MYSQL_ROOT_USER  is used ( and different from root), the user's custom files can't be loaded

**Steps to reproduce the issue:**
in the attached archive [test.zip](https://github.com/bitnami/bitnami-docker-mysql/files/5118821/test.zip):
1.  Launch the docker-compose.yml file in the archive: the database can't be started.  stop with `docker-compose down -v` to remove the volume
2. Change `MYSQL_ROOT_USER=root_doesnt_work` by `MYSQL_ROOT_USER=root`
3. Re launch the docker-compose.yml. The database is started.

**Describe the results you received:**

If MYSQL_ROOT_USER is set and different from ROOT, it's impossible to use custom files

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.12, build 48a66213fe

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 60
  Running: 0
  Paused: 0
  Stopped: 60
 Images: 584
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.826GiB
 Name: docker-desktop
 ID: 6FAL:OUFW:YGCO:3I6H:L4DP:SVUY:Z6FQ:M7KH:GZ7C:ZGYK:FGVI:PL2G
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-08-24T15:33:17.643960495Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Comment by icrc-fdeniger** [comment]
If I start the docker with `BITNAMI_DEBUG=true`, I get: 

```
mysql_1  | mysql 15:40:59.35 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
mysql_1  | mysql 15:40:59.35 DEBUG ==> Executing /docker-entrypoint-initdb.d/test.sql
mysql_1  | mysql 15:40:59.36 DEBUG ==> Executing SQL command:
mysql_1  | select 1
mysql_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1  | 2020-08-24T15:40:59.368218Z 12 [Note] Access denied for user 'root'@'localhost' (using password: YES)
mysql_1  | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
mysql_1  | mysql 15:41:01.38 DEBUG ==> Executing SQL command:
mysql_1  | select 1

```

**Comment by rafariossaa** [comment]
Hi, 
  Thanks for reporting this issue.
  I am creating an internal task to look deeper into this.
  We will come back to you as soon as we have news.

**Comment by FraPazGal** [comment]
Hello @icrc-fdeniger,

It seems that this was a bug in our code. When using a custom init file the container checks whether the database is up and running before executing it. The problem was that it always used the default root user `root` to make this check.

It should be fixed now, thanks for reporting this issue!

**Comment by icrc-fdeniger** [comment]
thanks a lot @rafariossaa  and @FraPazGal for the fix.

**Comment by rafariossaa** [comment]
Hi @icrc-fdeniger ,
  The fixes were introduced in the release 5.7.31-debian-10-r31.

**Comment by icrc-fdeniger** [comment]
Thanks. And will it be introduced in the image 5.7 ?

**Comment by rafariossaa** [comment]
@icrc-fdeniger Yes, as you can see [here](https://hub.docker.com/r/bitnami/mysql/tags), `5.7` is the same image (sha256: `9ff128b0faf9`) as `5.7-debian-10`, `5.7.31` and `5.7.31-debian-10-r34`.
