### ISSUE TITLE
How to capture logs in bitnami:mysql? 

### ISSUE THREAD

**Issue by AnkitaPadma** [bitnami/bitnami-docker-mysql#105]
I created a volume mapped to /bitnami/mysql/logs
but this folder is always empty and none of the querys or event or error are logged in this folder.

BTW, I also mapped opt/bitnami/mysql/logs, and got the mysqld.log file, but this doesnt provide the log I m looking for.
Basically I want to see what changes that were made to my db in the course of time..

Please suggest if any docker settings needs to be done.. or if i need to map the volume to some other location

**Comment by AnkitaPadma** [comment]
@pankaj-dahiya Any idea about this?

**Comment by javsalgar** [comment]
Hi,

Our containers are currently writing all the output to stdout, as suggested by the container best practices. Doesn't docker logs show the output you are looking for? Could it be that you need a more verbose log level?

**Comment by AnkitaPadma** [comment]
Hi @javsalgar Basically I m looking for mysql logs to be more precise, relating to the queries that get executed or changes in the mysql when the docker container is up.
The persistant data is stored in /bitnami/mysql/data ... similarly is there any way I can get the logs volume for mysql?

**Comment by javsalgar** [comment]
Hi,

The mysql.log file is actually a link to stdout. The reason for that is for the logs to be easily consumable by logging stacks like EFK or ELK.

```
lrwxrwxrwx 1 root root   11 Sep  3 15:36 mysqld.log -> /dev/stdout
```

That means that you may need a higher verbosity level in order to get the information you require. Also, would it make sense to you to make the logging redirection to stdout configurable?

**Comment by AnkitaPadma** [comment]
@javsalgar What is the use of  /bitnami/mysql/logs folder then? Just trying to better understand..

**Comment by javsalgar** [comment]
Hi,

That folder would not be used, what we state in the readme files is that data would be written in `/bitnami/mysql/data`. The log symlink is created in `/opt/bitnami/mysql/logs`.
