### ISSUE TITLE
changing permissions of '/proc/self/fd/1': Permission denied

### ISSUE THREAD

**Issue by Ashishyh** [bitnami/bitnami-docker-mysql#109]
########################################

bookinfo-demo-mysqldb-78c87d7684-z5tcl pod is not running and its in CrashLoopBackOff state

Error logs of the pod:
#####################################################################
[oc logs -f bookinfo-demo-mysqldb-78c87d7684-z5tcl
mysql 07:43:40.71 
mysql 07:43:40.71 Welcome to the Bitnami mysql container
mysql 07:43:40.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 07:43:40.71 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 07:43:40.71 Send us your feedback at containers@bitnami.com
mysql 07:43:40.72 
mysql 07:43:40.72 INFO  ==> ** Starting MySQL setup **
mysql 07:43:40.80 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
chmod: changing permissions of '/proc/self/fd/1': Permission denied

**Comment by andresbono** [comment]
Hi @Ashishyh, can you share how are you launching the chart? Can you also share details about your Kubernetes cluster?

**Comment by Ashishyh** [comment]
We are deploying application via cloudpak for management
Target cluster: Openshift version 4.3
https://cloudpak8s.io/mcm/cp4mcm_mcm_bookinfo/

**Comment by Ashishyh** [comment]
We are deploying application via cloudpak for management
Target cluster: Openshift version 4.3
https://cloudpak8s.io/mcm/cp4mcm_mcm_bookinfo/

**Comment by Ashishyh** [comment]
We are deploying application via cloudpak for management
Target cluster: Openshift version 4.3
https://cloudpak8s.io/mcm/cp4mcm_mcm_bookinfo/

**Comment by Ashishyh** [comment]
Hi @andresbono
We are deploying application via cloudpak for management
Target cluster: Openshift version 4.3
https://cloudpak8s.io/mcm/cp4mcm_mcm_bookinfo/

**Comment by andresbono** [comment]
Can you obtain the values being used to deploy the chart? It would be useful for us to be able to reproduce and understand the issue.

**Comment by icrc-fdeniger** [comment]
We face the issue and the issue is there if we try to customize the image
