### ISSUE TITLE
Feature request: Arm64 support for docker images

### ISSUE THREAD

**Issue by techknowlogick** [bitnami/bitnami-docker-mysql#112]
With the rise of platforms running on arm hardware (especially with k3s supporting many edge platforms), it would be great if this image could support arm64 too

**Comment by dani8art** [comment]
Hi @techknowlogick, we would really work on supporting ARM but unfortunately, we are a small team right now and we have a limited bandwidth to work on this. That would require major changes in our pipeline to support building & testing ARM containers.
