### ISSUE TITLE
Write permission denied in linux

### ISSUE THREAD

**Issue by AnkitaPadma** [bitnami/bitnami-docker-mysql#113]
mysql_1       | mysql 14:03:58.18
mysql_1       | mysql 14:03:58.18 Welcome to the Bitnami mysql container
mysql_1       | mysql 14:03:58.19 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql_1       | mysql 14:03:58.19 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql_1       | mysql 14:03:58.19
mysql_1       | mysql 14:03:58.19 INFO  ==> ** Starting MySQL setup **
mysql_1       | mysql 14:03:58.24 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql_1       | mysql 14:03:58.25 INFO  ==> Initializing mysql database
mysql_1       | mysql 14:03:58.25 DEBUG ==> Ensuring expected directories/files exist
mysql_1       | mysql 14:03:58.27 INFO  ==> Updating 'my.cnf' with custom configuration
mysql_1       | mysql 14:03:58.27 INFO  ==> Setting user option
mysql_1       | mysql 14:03:58.28 DEBUG ==> Setting user to 'admin' in mysql configuration file /opt/bitnami/mysql/conf/my.cnf
mysql_1       | mysql 14:03:58.28 INFO  ==> Setting default_authentication_plugin option
mysql_1       | mysql 14:03:58.28 DEBUG ==> Setting default_authentication_plugin to 'mysql_native_password' in mysql configuration file /opt/bitnami/mysql/conf/my.cnf
mysql_1       | mysql 14:03:58.29 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql_1       | mysql 14:03:58.30 INFO  ==> Installing database
mysql_1       | mysqld: Can't create/write to file '/bitnami/mysql/data/is_writable' (OS errno 13 - Permission denied)
mysql_1       | 2020-10-12T14:03:58.338414Z 0 [System] [MY-013169] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.21) initializing of server in progress as process 43
mysql_1       | 2020-10-12T14:03:58.339319Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
mysql_1       | 2020-10-12T14:03:58.339322Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
mysql_1       | 2020-10-12T14:03:58.343826Z 0 [ERROR] [MY-010460] [Server] --initialize specified but the data directory exists and is not writable. Aborting.
mysql_1       | 2020-10-12T14:03:58.343869Z 0 [ERROR] [MY-013236] [Server] The designated data directory /bitnami/mysql/data/ is unusable. You can remove all files that the server added to it.
mysql_1       | 2020-10-12T14:03:58.343915Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql_1       | 2020-10-12T14:03:58.344044Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.21)  Source distribution.
phpmyadmin-service | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.3. Set the 'ServerName' directive globally to suppress this message
phpmyadmin-service | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.3. Set the 'ServerName' directive globally to suppress this message
phpmyadmin-service | [Mon Oct 12 14:03:59.199922 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.11 configured -- resuming normal operations
phpmyadmin-service | [Mon Oct 12 14:03:59.201708 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
sentinel-monitor-db-backup_mysql_1 exited with code 1

**Comment by AnkitaPadma** [comment]
@juan131 Could you please help with this issue

I did try to add these in my Dockerfile:- 

RUN chown -R admin:admin /bitnami/mysql/data
RUN chmod 755 /bitnami/mysql/data
USER admin

But it still didnt resolve the issue

**Comment by FraPazGal** [comment]
Hi @AnkitaPadma,

Thanks for opening this issue! Could you share the `docker-compose.yaml` file you used? 

From what I see, you are mounting a local directory for persistence, is that right? In that case, you only need to modify the `chown` and `chmod` permissions of said folder for them to be usable for user 1001.

**Comment by AnkitaPadma** [comment]
Hi @FraPazGal , thanks for your reply.
As requested, below is the docker-compose.yaml code for your reference
version: '3'
services:
  mysql:
    build: .
    ports:
      - 3307:3306
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DEV}
      MYSQL_DATABASE: ${MYSQL_DATABASE_DEV}
      MYSQL_USER: ${MYSQL_USER_DEV}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_DEV}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      #BITNAMI_DEBUG: "true"
    volumes: 
      - ${MYSQL_DATA_DIR}:/bitnami/mysql/data
      - ${MYSQL_SCRIPT_DIR}:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin-service'
    restart: always
    links:
      - mysql
    environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DEV}
        MYSQL_USER: ${MYSQL_USER_DEV}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD_DEV}
    ports:
      - 8081:80
    volumes:
      - /sessions

**Comment by FraPazGal** [comment]
Hi @AnkitaPadma,

I'm not sure I understand why you are using a custom image instead of the default one. To solve the permissions error, you should only need to change the permissions of the local folder you are using as volume. I don't think there is any need to add new lines to the `Dockerfile`. Could you try using the default image in the `docker-compose.yaml` file and modify the folder permissions following my previous comment's guidelines?

**Comment by AnkitaPadma** [comment]
Thanks @FraPazGal 
Issue was resolved by adding permissions for the local volumes.

**Comment by AnkitaPadma** [comment]
@FraPazGal Hi, the issue re occurs on running the docker the second time. Only first time it resolves, as the new files that get written still dont have the permission
and to resolve everytime the permission modification is needed. Is there a workaround for that.

**Comment by dani8art** [comment]
Hi @AnkitaPadma,

Our containers are prepared to be run as non-root users so that you would need to modify the permissions of your local directory or use a docker volume instead. Please, try to execute the following

> Note: ${MYSQL_DATA_DIR} should exist before `docker-compose up`

```
$ sudo chmod -R g+wr ${MYSQL_DATA_DIR}
```

Otherwise, you also can use docker volume instead

```yaml
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
```

**Comment by AnkitaPadma** [comment]
@dani8art Thanks for the suggestion.
But still have to set the permissions twice.
In first docker run, the folder is present but empty, so here we set the permission for the write permission to be active for the user.
In the second run the folder has the dump files in it, so to set the permission for these now the -R sets on these..
so a min of 2 times is needed.

**Comment by FraPazGal** [comment]
Hi @AnkitaPadma,

Have you tried giving ownership of the local folder to user 1001? If I'm not mistaken, `chmod` will only change the permissions of existing files and not of new files created after. After `chmod`, please use:

```
$ sudo chown -R 1001 ${MYSQL_DATA_DIR}
```
