### ISSUE TITLE
bitnami/mysql:5.7.32 container CrashLoopBackOff when add connection_control plugin in my_custom.cnf

### ISSUE THREAD

**Issue by XC-L** [bitnami/bitnami-docker-mysql#115]
**Description**

bitnami/mysql:5.7.32.

How can I use the connection_control.so and validate_password.so plugins in this mysql image. When I add these plugins in my_custom.cnf like this:

```
[mysqld]
plugin-load-add=connection_control.so
connection-control=FORCE_PLUS_PERMANENT
connection-control-failed-login-attempts=FORCE_PLUS_PERMANENT
```

The container status is CrashLoopBackOff.

The container log like this:

```
mysql 12:19:58.94
mysql 12:19:58.94 Welcome to the Bitnami mysql container
mysql 12:19:58.95 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 12:19:58.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 12:19:58.95
mysql 12:19:58.95 INFO  ==> ** Starting MySQL setup **
mysql 12:19:58.97 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 12:19:58.99 INFO  ==> Initializing mysql database
mysql 12:19:59.02 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 12:19:59.04 INFO  ==> Injecting custom configuration 'my_custom.cnf'
mysql 12:19:59.05 INFO  ==> Installing database
```

It's over.

**Comment by juan131** [comment]
Hi @XC-L 

Could you please set the environment variable `BITNAMI_DEBUG=true` in your container? That will increase the logs verbosity, so we obtain more information about the reasons why it failed. 

Please share again the logs after doing so, thanks in advance.

**Comment by XC-L** [comment]
DEBUG log

mysql 16:35:45.92
mysql 16:35:45.92 Welcome to the Bitnami mysql container
mysql 16:35:45.93 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 16:35:45.93 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 16:35:45.93
mysql 16:35:45.93 INFO  ==> ** Starting MySQL setup **
mysql 16:35:45.96 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 16:35:45.98 INFO  ==> Initializing mysql database
mysql 16:35:45.99 DEBUG ==> Ensuring expected directories/files exist
mysql 16:35:46.02 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 16:35:46.03 DEBUG ==> Injecting custom configuration from my_custom.conf
mysql 16:35:46.03 INFO  ==> Injecting custom configuration 'my_custom.cnf'
mysql 16:35:46.04 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql 16:35:46.04 INFO  ==> Installing database
2020-11-23T08:35:46.564008Z 0 [Warning] InnoDB: New log files created, LSN=45790
2020-11-23T08:35:46.604005Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2020-11-23T08:35:46.667692Z 0 [ERROR] Can't open shared library '/opt/bitnami/mysql/plugin/connection_control.so' (errno: 2 /opt/bitnami/mysql/plugin/connection_control.so: cannot open shared object file: No such file or directory)
2020-11-23T08:35:46.667728Z 0 [ERROR] Couldn't load plugin named 'connection_control.so' with soname 'connection_control.so'.
2020-11-23T08:35:46.667850Z 0 [ERROR] unknown variable 'connection-control=FORCE_PLUS_PERMANENT'
2020-11-23T08:35:46.667859Z 0 [ERROR] Aborting

**Comment by juan131** [comment]
Hi @XC-L 

It seems the error is quite clear:

```
2020-11-23T08:35:46.667692Z 0 [ERROR] Can't open shared library '/opt/bitnami/mysql/plugin/connection_control.so' (errno: 2 /opt/bitnami/mysql/plugin/connection_control.so: cannot open shared object file: No such file or directory)
```

You're trying to use a plugins that's not included in the image. I'm afraid that, in this case, you'll have to create your own custom image (based on this one) adding the missing libraries. Find more information in the link below:

- https://github.com/bitnami/bitnami-docker-mysql#extend-this-image

**Comment by XC-L** [comment]
thank you, i know how to deal with this
