### ISSUE TITLE
Override main configuratiuon file not work

### ISSUE THREAD

**Issue by serg-bs** [bitnami/bitnami-docker-mysql#116]
**Description**

Description below does not work
https://github.com/bitnami/bitnami-docker-mysql/#overwrite-the-main-configuration-file

**Steps to reproduce the issue:**

1. I run bitnami/mysql and copy content of /opt/bitnami/mysql/conf/my.cnf to /path/to/my.cnf
2. `docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=root -v /path/to/my.cnf:/opt/bitnami/mysql/conf/my.cnf:ro bitnami/mysql:latest`

**Describe the results you received:**

In logs 
```
mysql 11:10:06.10 INFO  ==> Initializing mysql database
mysql 11:10:06.12 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 11:10:06.12 INFO  ==> Installing database

```
And container stop

**Describe the results you expected:**

I expect container will start

**Additional information you deem important (e.g. issue happens only occasionally):**

I found it then try to use mysql helm chart and set up master.config

**Comment by serg-bs** [comment]
I mistake. If I take it from docker image it work. But not work from kubernetes 
`
Default
default_authentication_plugin=mysql_native_password
skip-name-resolve
explicit_defaults_for_timestamp
basedir=/opt/bitnami/mysql
plugin_dir=/opt/bitnami/mysql/plugin
port=3306
socket=/opt/bitnami/mysql/tmp/mysql.sock
datadir=/bitnami/mysql/data
tmpdir=/opt/bitnami/mysql/tmp
max_allowed_packet=16M
bind-address=0.0.0.0
pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
log-error=/opt/bitnami/mysql/logs/mysqld.log
character-set-server=UTF8
collation-server=utf8_general_ci

[client]
port=3306
socket=/opt/bitnami/mysql/tmp/mysql.sock
default-character-set=UTF8
plugin_dir=/opt/bitnami/mysql/plugin

[manager]
port=3306
socket=/opt/bitnami/mysql/tmp/mysql.sock
pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
`
I will be investigate it

**Comment by miguelaeh** [comment]
Hi @serg-bs ,
Did you close the issue because you found the solution?

**Comment by serg-bs** [comment]
I make some investigation. And find what I make mistake in configuration.
For example forget in my.cnf
[mysqld] 
or use deprecated in 8.0 parameters 
query_cache_limit=1M
query_cache_size=8M

In this case you see in logs just I describe. I prefer if will be some exeption that tells - "you configuration is wrong query_cache_size is depricated"  or "you configuration is wrong not found mysqld" 
But I don't think it's a bug.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing your findings.
  You can enable debug mode by setting this environment variable: `BITNAMI_DEBUG=1` and that should give more information.
