### ISSUE TITLE
How to make changes to the db table or stored procedure, with already old persistent data.

### ISSUE THREAD

**Issue by AnkitaPadma** [bitnami/bitnami-docker-mysql#117]
My docker was working fine. 
But then I wanted to make a small change in my procedure.sql file and rerun the docker.
But the change is not getting applied?
i did the following steps

- docker-compose down
- docker system prune -a
- made the changes to the file and saved it
- docker-compose up -d --build

But i dont the see the change in the operations.
Do I need to delete the persistent data present in my mapped volume to get the changes reflected?

Note:- IN my procedure.sql my first line is to drop the procedure if it already exists. So I really dont know why the changes are not getting applied if i just build the docker again. But if i clean the persistent volume data and then run the docker it works perfectly fine.

Please suggest a proper way to manage this issue, as I dont want to lose my captured data.

**Comment by AnkitaPadma** [comment]
@javsalgar @FraPazGal please suggest

**Comment by miguelaeh** [comment]
Hi @AnkitaPadma ,
I am not sure about what is and how are you including your `procedure.sql` file in the image. Could you clarify that?

**Comment by AnkitaPadma** [comment]
@miguelaeh Basically I map all the scripts to binami docker that it can use to initialize the db
- ${MYSQL_SCRIPT_DIR}:/docker-entrypoint-initdb.d/

**Comment by miguelaeh** [comment]
Hi @AnkitaPadma ,
It is because there is a condition that checks if the scripts have already been executed:
```
if [[ -n $(find /docker-entrypoint-initdb.d/ -type f -regex ".*\.\(sh\|sql\|sql.gz\)") ]] && [[ ! -f "$DB_DATA_DIR/.user_scripts_initialized" ]] ; then
```

When you remove the data directory you are also removing the `.user_scripts_initialized` file, so it allows you to run it again.
This is designed to execute the script only in the first run. To be able to re-execute them you would need to delete the `.user_scripts_initialized` before restart your container.

**Comment by AnkitaPadma** [comment]
Hi @miguelaeh 
Can I just delete this .user_scripts_initialized file? Do I need any specific permission for this or any specific command or just sudo rm would do? Also will deleting this file cause any impact on the records added previously?

**Comment by miguelaeh** [comment]
Hi @AnkitaPadma ,
I think so, just deleting that file you will be able to execute your scripts again. I think the impact depends on what your scripts are doing so I recommend you to test it before modifying your production environment.

**Comment by AnkitaPadma** [comment]
Hi @miguelaeh , 
I tried by deleting the file, and running the docker again, but the file didnt recreate.
Could you please try and let me know the exact steps.

**Comment by miguelaeh** [comment]
Hi @AnkitaPadma ,
Is your script getting executed again after deleting the file? If it is executed the `.user_script_initialized` should be created again since it is just a touch.
Can you share your script to test it on our side?

**Comment by AnkitaPadma** [comment]
The script is a *.sql file with the following format
CREATE DATABASE IF NOT EXISTS `TestDB`;
USE `TestDB`;

CREATE TABLE IF NOT EXISTS `Roles` (
 `RoleID` int NOT NULL AUTO_INCREMENT,
  `RoleName` varchar(45) NOT NULL,
 PRIMARY KEY (`RoleID`),
  UNIQUE KEY `RoleName_UNIQUE` (`RoleName`)
);

and for mapping the data to the volumes :- 
${MYSQL_SCRIPT_DIR}:/docker-entrypoint-initdb.d/

*.sql file is placed in the path {MYSQL_SCRIPT_DIR} on my local machine.
And I take the data backup as ${MYSQL_DATA_DIR}:/bitnami/mysql/data

Run the docker the first time add some records to the table.
Then i stop the docker and even clean the container images by using prune cmd

Next as suggested by you, I delete the .user_script_initialized from my {MYSQL_DATA_DIR}
make the changes to the *.sql to as below (Column Rolename changed to Name)

CREATE DATABASE IF NOT EXISTS `TestDB`;
USE `TestDB`;
CREATE TABLE IF NOT EXISTS `Roles` (
 `RoleID` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(45) NOT NULL,
 PRIMARY KEY (`RoleID`),
  UNIQUE KEY `Name_UNIQUE` (`Name`)
);

And run the docker again

**Comment by AnkitaPadma** [comment]
Hi @miguelaeh,
I didn some changes and now the .user_script_initialized  is recreated.
But still I dont see the changes reflicted.

So below is the test scenario I tried:-

The script is a *.sql file with the following format
CREATE DATABASE IF NOT EXISTS TestDB;
USE TestDB;

CREATE TABLE IF NOT EXISTS Roles (
RoleID int NOT NULL AUTO_INCREMENT,
RoleName varchar(45) NOT NULL,
PRIMARY KEY (RoleID),
UNIQUE KEY RoleName_UNIQUE (RoleName)
);

and for mapping the scripts to the volumes :-
${MYSQL_SCRIPT_DIR}:/docker-entrypoint-initdb.d/

*.sql file is placed in the path {MYSQL_SCRIPT_DIR} on my local machine.
And I take the data backup as ${MYSQL_DATA_DIR}:/bitnami/mysql/data

Run the docker the first time add some records to the table.
Then i stop the docker and even clean the container images by using prune cmd

Next as suggested by you, I delete the .user_script_initialized from my {MYSQL_DATA_DIR}
make the changes to the *.sql to as below (Column Rolename changed to Name)

CREATE DATABASE IF NOT EXISTS TestDB;
USE TestDB;
CREATE TABLE IF NOT EXISTS Roles (
RoleID int NOT NULL AUTO_INCREMENT,
Name varchar(45) NOT NULL,
PRIMARY KEY (RoleID),
UNIQUE KEY Name_UNIQUE (Name)
);

And run the docker again

Hope this provide the idea about the requirement.

**Comment by miguelaeh** [comment]
Hi @AnkitaPadma ,
It seems your changes are not applied because you are using the `IF NOT EXISTS` in the create statements. Since the database will exist it will not be executed again.
I have tested it on my side creating a second table after deleting the `user_scripts_initialized` and it has worked fine.
You will need to modify your script since the logic will not create the database again because it was already created in the previous execution.

**Comment by AnkitaPadma** [comment]
Hi @miguelaeh ,
To resolve the issue you pointed out, I added a alter command in the script and it worked fine, instead of directly modifying the table schema as shown previously.

But again as Alter IGNORE is deprecated now, so in the consecutive docker run,  docker fails as the alter command is trying to alter something which is already previously altered. And hence **.user_scripts_initialized** is not getting created.

So how to manage this?

**Comment by miguelaeh** [comment]
Hi @AnkitaPadma ,
> So in the consecutive docker run, docker fails as the alter command is trying to alter something which is already previously altered.
I am sorry I don't fully understand this part, could you provide more information? Maybe also share the script you are using? I would say you should be able to alter twice without errors.

**Comment by AnkitaPadma** [comment]
Hi @miguelaeh ,

As requested please find the script code as below:-

**Initial script should be** 
CREATE DATABASE IF NOT EXISTS TestDB;
USE TestDB;

CREATE TABLE IF NOT EXISTS Roles (
RoleID int NOT NULL AUTO_INCREMENT,
RoleName varchar(45) NOT NULL,
PRIMARY KEY (RoleID),
UNIQUE KEY RoleName_UNIQUE (RoleName)
);

**Updated script with alter command**

CREATE DATABASE IF NOT EXISTS TestDB;
USE TestDB;

CREATE TABLE IF NOT EXISTS Roles (
RoleID int NOT NULL AUTO_INCREMENT,
RoleName varchar(45) NOT NULL,
PRIMARY KEY (RoleID),
UNIQUE KEY RoleName_UNIQUE (RoleName)
);

ALTER TABLE Roles RENAME COLUMN RoleName  TO Name;

**Comment by marcosbc** [comment]
Hi @AnkitaPadma, it sounds to me like you're expecting init scripts to be executed for each run, is that correct?

Note that init scripts are meant to be executed only during the first initialization (i.e. when the DB is populated for the first time). It is implemented like that by design.

If you wish to change that behavior, you'd need to fork the Bitnami MySQL container image. You could modify (remove) this line to get that working on your side: https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L371
