### ISSUE TITLE
Support for MySQL 5.6 and older versions

### ISSUE THREAD

**Issue by reneroboter** [bitnami/bitnami-docker-mysql#120]
Hi,

the issue is quite simple. I'm looking for a support for older MySQL versions e.g 5.6 and 5.5. Why is there no container version? 

Greeting
René

**Comment by FraPazGal** [comment]
Hello @reneroboter,

We always try to offer our solutions on the most popular versions but, as we are a fairly small team, there is so much we can  take in. Unfortunately, being older versions, we are not currently interested in adding them to our catalog. I hope versions 5.7 or 8.0 may be of use for you.

**Comment by reneroboter** [comment]
Hi @FraPazGal,

thanks for your fast reply. We use [Lando](https://lando.dev/) for our local dev environments. Lando MySQL support based on your images. Actually we need support for older MySQL versions. Is there an instruction guide to build my own MySQL 5.6 container maybe based on your 5.7? I checked it yesterday, and it seems to me that you provide special MySQL installation packages for your container. I'm right? 

Greeting
René

**Comment by FraPazGal** [comment]
Hi @reneroboter,

Yes, we compile our own installation packages. I looked it up, but we never got to support mysql `5.6` as a container so we didn't get to compile a package for that version, sorry for not being able to help you more.
