### ISSUE TITLE
Error check fail init db

### ISSUE THREAD

**Issue by armandleopold** [bitnami/bitnami-docker-mysql#125]
**Description**

The pod fails starting at first launch.

**Steps to reproduce the issue:**
1. install the bitnami/mysql with **persistence: enabled: true**
 
**Describe the results you received:**

```yaml
2021-04-15T08:56:16.580451Z 4 [ERROR] [MY-013183] [InnoDB] Assertion failure: trx0undo.cc:1669:mach_read_from_2(undo_page + TRX_UNDO_PAGE_HDR + TRX_UNDO_PAGE_TYPE) == TRX_UNDO_UPDATE thread 139881279395584
```

**Describe the results you expected:**

No error

**Additional information you deem important (e.g. issue happens only occasionally):**

- Set static credentials with :

```yaml
  auth: 
    rootPassword: test
    database: testdb
    username: test
    password: test
```

- Set initdb script : 

```yaml
  initdbScripts:
    initscript.sql: |-
      CREATE USER 'reader'@'%' IDENTIFIED BY 'test';
      GRANT SELECT, LOCK TABLES, SHOW VIEW, EVENT, TRIGGER  ON *.* TO 'reader'@'%';

      CREATE USER 'testssl'@'%' IDENTIFIED BY 'test' REQUIRE SSL;
      GRANT ALL PRIVILEGES ON `testdb`.* TO 'testssl'@'%' WITH GRANT OPTION;
      
      FLUSH PRIVILEGES;
```

**Version**

```
mysql:
  image:
    tag: 8.0.23-debian-10-r80
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Environment : 

* Kubernetes : v1.15.5
* helm : v3

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Could you specify more details about your Kubernetes cluster? Seems to be a PVC issue to me. Which PVC technology are you using?

**Comment by armandleopold** [comment]
Yes we have investigated the problem.
The helm chart runs correctly with the bitnami version : 8.0.18
We use StorageOS as Storage provider.

**Comment by javsalgar** [comment]
Ok. Just for ensuring that the issue lies in the storage provider. Could you try launching the chart with the persistence values disabled? If it goes fine then there might be an incompatibility with the provider introduced in later versions of MySQL.

**Comment by armandleopold** [comment]
Yep, Done, and it works fine without persistence.
I had the same conclusion than you. I posted the issue just to be sure there is no other sources of errors possible.
If we can agree on the fact that this is an incompatibility with the storage provider, then let's close the issue here.
