### ISSUE TITLE
[Feature Request]Support subPath for data volumn

### ISSUE THREAD

**Issue by alex-lx** [bitnami/bitnami-docker-mysql#126]
bitnami postgresql support using `persistence.subPath` to specify the `subPath` of the mount volumes, it would be nice to bring it to mysql.

**Comment by marcosbc** [comment]
Hi, @alex-lx, please note that we are open for external contributions. If you think this feature would be useful, feel free to send a PR, we'd be glad to help with the review and release processes.

**Comment by alex-lx** [comment]
Sorry, I've made a mistake. I should post this feature request in [charts's repo](https://github.com/bitnami/charts/tree/master/bitnami/mysql) rather here. Sorry to bother you guys.
