### ISSUE TITLE
The README file in the repo references MariaDB variables

### ISSUE THREAD

**Issue by Pr-Pierre** [bitnami/bitnami-docker-mysql#132]
Hi,

The README file in the repo references MariaDB variables at https://github.com/bitnami/bitnami-docker-mysql/blob/master/README.md#setting-character-set-and-collation instead of 

* MYSQL_CHARACTER_SET
* MYSQL_COLLATE

**Comment by marcosbc** [comment]
Hi, you seem to be right. We're going to fix this, thanks for reporting!

**Comment by marcosbc** [comment]
This issue is already fixed. It seems I forgot to update this issue and close. Thanks again for reporting!
