### ISSUE TITLE
mysql-secondary Liveness probe failed @k8s

### ISSUE THREAD

**Issue by wyq984700527** [bitnami/bitnami-docker-mysql#136]
## install
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install my-release bitnami/mysql

## status
mysql-primary-0 running success，but mysql-secondary-0 liveness probe fail as follows
is this a bug? 
![image](https://user-images.githubusercontent.com/52362142/129032379-1f44edcf-1fdb-4746-bb99-46dc743a632a.png)

![image](https://user-images.githubusercontent.com/52362142/129032169-a6fffadb-558d-4b29-875b-9c56df67dd6e.png)

**Comment by migruiz4** [comment]
Hi @wyq984700527,

Is it possible you previously installed the Helm chart with the same release name? 

When you uninstall the `mysql`, persistent volumes are not removed and will be reused if the chart is reinstalled.

To solve this issue:
 1. Uninstall the chart
    ```
    helm uninstall my-release
    ```
 2. Check PVCs
    ```
    $ kubectl get pvc
    NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
    data-MY-RELEASE-mysql-0     Bound    pvc-ec438751-efa8-4eb2-ad91-f5d808f913ba   8Gi        RWO            standard       1m52s
    ```
 3. Delete PVCs
    ```
    kubectl delete pvc data-MY-RELEASE-mysql-0
    ```
 4. Re-install the chart
    ```
    helm install my-release bitnami/mysql
    ```





You can find more information in the following link: https://docs.bitnami.com/kubernetes/faq/troubleshooting/troubleshooting-helm-chart-issues/

**Comment by wyq984700527** [comment]
> Hi @wyq984700527,
> 
> Is it possible you previously installed the Helm chart with the same release name?
> 
> When you uninstall the `mysql`, persistent volumes are not removed and will be reused if the chart is reinstalled.
> 
> To solve this issue:
> 
> 1. Uninstall the chart
>    ```
>    helm uninstall my-release
>    ```
> 2. Check PVCs
>    ```
>    $ kubectl get pvc
>    NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
>    data-MY-RELEASE-mysql-0     Bound    pvc-ec438751-efa8-4eb2-ad91-f5d808f913ba   8Gi        RWO            standard       1m52s
>    ```
> 3. Delete PVCs
>    ```
>    kubectl delete pvc data-MY-RELEASE-mysql-0
>    ```
> 4. Re-install the chart
>    ```
>    helm install my-release bitnami/mysql
>    ```
> 
> You can find more information in the following link: https://docs.bitnami.com/kubernetes/faq/troubleshooting/troubleshooting-helm-chart-issues/

my error is because of the startUpProbe invalid in k8s-1.16, now i fix it, thanks a lot.

**Comment by migruiz4** [comment]
Thank you for reporting this issue @wyq984700527 and sharing with us the solution. 

Indeed the Mysql chart has startupProbe enabled by default and would fail in Kubernetes prior to 1.18
We enabled startupProbes to make pods initialization faster when needed, but I have created an internal task to discuss this problem and find a solution.
