### ISSUE TITLE
Why bitnami mysql image is bigger than official one?

### ISSUE THREAD

**Issue by Mutuduxf** [bitnami/bitnami-docker-mysql#140]
I have pulled the mysql image base on bitnami and offical ,and the bitnami one is 729MB but the offical one is 516MB.Cause minideb the bitnami one is generally smaller than the offical image.What is the cause of bitnami/mysql is bigger than the offical one?

REPOSITORY                       TAG                                 IMAGE ID          CREATED         SIZE
bitnami/mysql                    8.0.27-debian-10-r22     510e660e8a53   11 hours ago   729MB
mysql                                  8.0.27                             ecac195d15af     3 weeks ago    516MB

**Comment by yilmi** [comment]
Hi @Mutuduxf,

Having a look at the filesystem (I manually removed some entries for readability):
```
❯ docker run --entrypoint "/bin/bash" -it mysql:latest -c "du -sh /* 2>/dev/null"
4.8M	/bin
13M	/lib
383M	/usr
98M	/var
```

```bash
❯ docker run --entrypoint "/bin/bash" -it bitnami/mysql:latest -c "du -sh /* 2>/dev/null"
5.1M	/bin
1.4M	/etc
12M	/lib
618M	/opt
3.3M	/sbin
61M	/usr
6.4M	/var
```

If you modify these commands, you'll see that in the bitnami container, we're installing all the tools from the mysql project.

This is also visible from their dockerfile (that you can find on DockerHub):

- [Dockerfile for mysql 8.0.27](https://github.com/docker-library/mysql/blob/15fe7357b165ee8aaa3ce165386f910a53a75087/8.0/Dockerfile.debian
)

Let me know if that answers your question.

**Comment by Mutuduxf** [comment]
> Hi @Mutuduxf,
> 
> Having a look at the filesystem (I manually removed some entries for readability):
> 
> ```
> ❯ docker run --entrypoint "/bin/bash" -it mysql:latest -c "du -sh /* 2>/dev/null"
> 4.8M	/bin
> 13M	/lib
> 383M	/usr
> 98M	/var
> ```
> 
> ```shell
> ❯ docker run --entrypoint "/bin/bash" -it bitnami/mysql:latest -c "du -sh /* 2>/dev/null"
> 5.1M	/bin
> 1.4M	/etc
> 12M	/lib
> 618M	/opt
> 3.3M	/sbin
> 61M	/usr
> 6.4M	/var
> ```
> 
> If you modify these commands, you'll see that in the bitnami container, we're installing all the tools from the mysql project.
> 
> This is also visible from their dockerfile (that you can find on DockerHub):
> 
> * [Dockerfile for mysql 8.0.27](https://github.com/docker-library/mysql/blob/15fe7357b165ee8aaa3ce165386f910a53a75087/8.0/Dockerfile.debian)
> 
> Let me know if that answers your question.

Hi @yilmi ,Thank you for answering my question.I am selecting for our test env and the image size is one of the factors to consider.

**Comment by yilmi** [comment]
Along with the image size, I would also consider the tools that you may need for your operations. You could always create a Dockerfile based on our image and removing the tools you don't need too.

**Comment by Mutuduxf** [comment]
> Along with the image size, I would also consider the tools that you may need for your operations. You could always create a Dockerfile based on our image and removing the tools you don't need too.

Hi yilmi,thx for your reply,I will modify the dockerfile.
