### ISSUE TITLE
Failed to set datadir to '/opt/bitnami/mysql/data/'

### ISSUE THREAD

**Issue by alinturbut** [bitnami/bitnami-docker-mysql#141]
**Description**

**Steps to reproduce the issue:**

1. Get the replication docker-compose.yml
2. Run docker-compose up -d

MySQL is not seen running and connecting to the port from localhost will just trigger a closed connection. If I try to run mysqld from inside the container, I get `Failed to set datadir to '/opt/bitnami/mysql/data/'`.

**Comment by carrodher** [comment]
I am not able to reproduce the issue. I cloned this repository and deployed the _docker-compose-replication.yml_ by running `docker-compose up`. Everything is up and running without any issue:

```console
$ docker ps
CONTAINER ID   IMAGE               COMMAND                  CREATED         STATUS                   PORTS                     NAMES
cb5effd4c6ac   bitnami/mysql:8.0   "/opt/bitnami/script…"   7 minutes ago   Up 7 minutes (healthy)   0.0.0.0:49178->3306/tcp   bitnami-docker-mysql_mysql-slave_1
81fcf0b6ae97   bitnami/mysql:8.0   "/opt/bitnami/script…"   7 minutes ago   Up 7 minutes (healthy)   0.0.0.0:49177->3306/tcp   bitnami-docker-mysql_mysql-master_1
```

**Comment by alinturbut** [comment]
To be honest not sure what the issue was. Deleted everything (pruned volumes) and redone and now it works.
