### ISSUE TITLE
Add the ability to run idempotent scripts on MySQL start up (similar to /docker-entrypoint-initdb.d)

### ISSUE THREAD

**Issue by ikemtz** [bitnami/bitnami-docker-mysql#143]
### Name and Version

bitnami/mysql:latest

### What is the problem this feature will solve?

My team and I need to run idempotent SQL scripts on MySQL start, and after the database has been initialized.  The current "/docker-entrypoint-initdb.d/" logic won't do because these scripts have to run after the database has been initialized.

### What is the feature you are proposing to solve the problem?

Add a "/docker-entrypoint-startdb.d" folder and have it behave the same as"/docker-entrypoint-initdb.d/", only remove the check for the ".user_scripts_initialized" file.

### What alternatives have you considered?

We have tried to run our SQL scripts within a Kubernetes [PostStart life cycle hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks) but this fails as the MySql hasn't started in the container yet.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! The team will take a look.
