### ISSUE TITLE
Mysql container restarting with exit code 1

### ISSUE THREAD

**Issue by ranjanp75** [bitnami/bitnami-docker-mysql#145]
### Name and Version

bitnami/mysql: 8.0.28-debian-10-r81

### What steps will reproduce the bug?

The bug is not reproducing consistently. The container restarts continuously with exit code 1

### What is the expected behavior?

The docker container should not restart continuously 

### What do you see instead?

The following error is seen on enabling BITNAMI_DEBUG=true to the container environment.
The logs are as follows:
```
mysql 06:50:33.30.    
mysql 06:50:33.30 Welcome to the Bitnami mysql container
mysql 06:50:33.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 06:50:33.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 06:50:33.40 
mysql 06:50:33.49 INFO  ==> ** Starting MySQL setup **
mysql 06:50:33.80 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 06:50:33.90 INFO  ==> Initializing mysql database
mysql 06:50:34.00 DEBUG ==> Ensuring expected directories/files exist
mysql 06:50:34.20 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 06:50:34.20 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql 06:50:34.20 INFO  ==> Installing database
mysqld: [ERROR] Failed to open required defaults file: /opt/bitnami/mysql/conf/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
```

### Additional information

The user used is root and has access to the config file and the config file is valid. I am facing this issue only on some setups. Could anyone please help me with this issue? Appreciate the time and efforts. Thanks

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate the docker-compose file or parameters you are using ?
