### ISSUE TITLE
lower_case_table_names appear to be '0' although configuration is '1'

### ISSUE THREAD

**Issue by royi-klein** [bitnami/bitnami-docker-mysql#146]
### Name and Version

mysql:8.0.29

### What steps will reproduce the bug?

Upgrade MySQL from previous versions (8.0.28 and below where lower_case_table_names=1)
Have the following config file: `/opt/bitnami/mysql/conf/bitnami/my_custom.cnf` 
Have the following line:
```
lower_case_table_names=1
```

### What is the expected behavior?

Upgrade process completed successfully

### What do you see instead?
```
[ERROR] [MY-011087] [Server] Different lower_case_table_names settings for server ('0') and data dictionary ('1')
[ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
[ERROR] [MY-010119] [Server] Aborting
```

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami MySQL container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
