### ISSUE TITLE
How to compile mysql-5.7.26 for docker image on ARM64

### ISSUE THREAD

**Issue by Yemacs** [bitnami/bitnami-docker-mysql#147]
### Name and Version

bitnami/mysql-5.7.26

### What is the problem this feature will solve?

can you share MySQL-5.7.26 Compile args？I want to build docker image on arm64，like this:

源码配置选项 | 默认值 | 定制值
-- | -- | --
CMAKE_INSTALL_PREFIX | /usr/local/mysql | /mysql/app
MYSQL_DATADIR |   | /mysql/product/data
DEFAULT_CHARSET | latin1 | utf8mb4
DEFAULT_COLLATION | latin1_swedish_ci | utf8mb4_general_ci
INSTALL_SECURE_FILE_PRIVDIR | platform specific | /mysql/product/mysql-files
ENABLED_LOCAL_INFILE | OFF | ON
MYSQL_TCP_PORT | 3306 | 33061
SYSCONFDIR |   | /mysql/app
MYSQL_UNIX_ADDR | /tmp/mysql.sock | /mysql/product/data/mysql.sock
COMPILATION_COMMENT |   | MySQL Server (GPL) Customised Version by XUH
WITH_BOOST |   | /soft/boost_1_59_0
WITH_ARCHIVE_STORAGE_ENGINE |   | 1
WITH_BLACKHOLE_STORAGE_ENGINE |   | 1
WITH_PERFSCHEMA_STORAGE_ENGINE |   | 1
WITH_EXAMPLE_STORAGE_ENGINE |   | 1
WITH_FEDERATED_STORAGE_ENGINE |   | 1
WITH_PARTITION_STORAGE_ENGINE |   | 1

### What is the feature you are proposing to solve the problem?

thanks

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
