### ISSUE TITLE
error booting

### ISSUE THREAD

**Issue by jstdoit** [bitnami/bitnami-docker-mysql#24]
```log
INFO  Initializing mysql
1/25/2017 7:21:09 PMError executing 'postInstallation': 2017-01-25T11:21:09.403125Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
1/25/2017 7:21:09 PM2017-01-25T11:21:09.406487Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
1/25/2017 7:21:09 PM2017-01-25T11:21:09.406549Z 0 [ERROR] Aborting
```

**Comment by sameersbn** [comment]
@jstdoit I tested using the [docker-compose.yml](https://raw.githubusercontent.com/bitnami/bitnami-docker-mysql/master/docker-compose.yml) from the repo and see no issues. Could you provide some more information that would allow us to reproduce this issue?

The [issues](https://github.com/bitnami/bitnami-docker-mysql#issues) section of the readme lists some of the information that you should attach to your issue report. Additionally let us know the docker platform in use (`docker-engine` on Linux, Docker for Windows, Docker for Mac, etc).

**Comment by jstdoit** [comment]
sorry for the bad format. As i'm using Rancher, so I offer infos as follows:

Host OS: CentOS 7.1
Docker version: 1.13.0
Output of docker info: 1.13.0

**Comment by sameersbn** [comment]
I setup a Rancher node with CentOS 7.3 (VM on GCE) running docker 1.13.0 using instructions from https://docs.docker.com/engine/installation/linux/centos/ and launched MySQL using the following compose spec and was not able to reproduce the issue.

```
version: '2'

services:
  mysql:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306'
    volumes:
      - 'mysql_data:/bitnami/mysql'

volumes:
  mysql_data:
    driver: local
```

If possible, can you share instructions that will allow us to duplicate this issue?
