### ISSUE TITLE
env_var are defined as MARIADB

### ISSUE THREAD

**Issue by pascalandy** [bitnami/bitnami-docker-mysql#4]
Hi,

I find it confusing that this project is using ENV_VAR as MARIADB_

i.e.
`docker run --name mysql -e MARIADB_ROOT_PASSWORD=password123 bitnami/mysql:latest`

Why is that ?

**Comment by sameersbn** [comment]
Thanks for pointing it out @pascalandy. It's a typo in the README. All variables should have the `MYSQL_` prefix.
