### ISSUE TITLE
Run custom script after db/container creation

### ISSUE THREAD

**Issue by sagaranand015** [bitnami/bitnami-docker-mysql#41]
So, I was trying to run a custom db script after passing the database name in the run container command. This does not seem to be one of the supported features. 
I did try to append the mysql command for running the required custom script to the init.sh script, but it won't let me run any mysql commands unless the container is setup completely. 
Is there any other workaround for achieving this? 

Or, is there a possibility to support such a usecase?

Thanks

**Comment by juan131** [comment]
Hello @sagaranand015 

Sorry for the delay on coming back to you. I guess you want to be able to run something like:

```
 docker run --name mysql -e ALLOW_EMPTY_PASSWORD=yes \
    -e MYSQL_DATABASE=my_database 
    -e MYSQL_SCRIPT='my custom mysql script' 
    bitnami/mysql:latest
```

The current supported parameters that can be modified using environment variables are:

- ALLOW_EMPTY_PASSWORD
- MYSQL_DATABASE
- MYSQL_MASTER_HOST
- MYSQL_MASTER_PORT_NUMBER
- MYSQL_MASTER_ROOT_PASSWORD
- MYSQL_MASTER_ROOT_USER
- MYSQL_PASSWORD
- MYSQL_PORT_NUMBER
- MYSQL_REPLICATION_MODE
- MYSQL_REPLICATION_PASSWORD
- MYSQL_REPLICATION_USER
- MYSQL_ROOT_PASSWORD
- MYSQL_ROOT_USER
- MYSQL_USER

Therefore, I am afraid you can't use this approach to do so. 

Regarding appending the MySQL command, you should not modify the `init.sh` or `app-entrypoint.sh` initialisation scripts. Those scripts are intended to start the services.

**Comment by tompizmor** [comment]
@sagaranand015  This is just a note to let you know that now it is possible to run custom initialization scripts. Please take a look to the [README](https://github.com/bitnami/bitnami-docker-postgresql#initializing-a-new-instance)

**Comment by sagaranand015** [comment]
Thank you @tompizmor for this. I guess the issue can be closed now.
