### ISSUE TITLE
Disable replica binlog

### ISSUE THREAD

**Issue by rdonadono** [bitnami/bitnami-docker-mysql#42]
Hi,

I need to disable binlog on my cluster of mysql slave.

I have created my_custom.cnf and mounted on containers but the options is ignored, how "--skip-log-bin".

How can fix it? I don't find doc about this.

Thanks,
Raffaele.

**Comment by juan131** [comment]
Could you try connecting to the Slaves and editing the file `/opt/bitnami/mysql/conf/my.cnf` so you add the `skip-log-bin` option under the section `[mysqld]`? Then you need to restart MySQL on each slave by running the command:

```
nami restart mysql
```
