### ISSUE TITLE
Usage of docker secrets

### ISSUE THREAD

**Issue by richardtape** [bitnami/bitnami-docker-mysql#44]
First, thank you so much for providing these images, docs, support, updates etc. It's hugely appreciated.

Right now, the username and passwords are stored as environment variables. Docker now has the idea of secrets which are available to be used with or without a docker swarm.

Would you consider switching from environment variables to docker secrets?

**Comment by prydonius** [comment]
@richardtape I think that makes a lot of sense, after all - we use secrets in our Kubernetes charts. Since I haven't looked at Docker's secret handling, are these easily exposed via env vars?

**Comment by richardtape** [comment]
Sadly not, some changes need to be made under the hood. But, they can be backwards compatible.

https://docs.docker.com/engine/swarm/secrets/ is the docs (but you can use them without swarm). Personally, I'm a fan of docker compose, so am interested in how it can play out there. And, as a WordPress dev, I found the following

https://github.com/docker-library/wordpress/blob/28bdfe39463a2e73effd6aa49a6a97821d148cff/docker-entrypoint.sh

If you take a look at the `file_env` function it allows for environment variables, such as `WORDPRESS_DB_PASSWORD` which is what they have had for a while, but they've also embraced docker secrets by allowing for `WORDPRESS_DB_PASSWORD_FILE` as a secret.

**Comment by prydonius** [comment]
Interesting, thanks for the pointers @richardtape, we'll look into it!

**Comment by teddy-dubal** [comment]
Hi @richardtape  , did you found a workaround  ?

**Comment by richardtape** [comment]
I did not.

**Comment by sameersbn** [comment]
please see my comment (workaround) here https://github.com/bitnami/minideb/issues/40#issuecomment-354939530
I am not sure if it'll work (or if it can be made to work) with docker swarm as I have very little experience using it.

**Comment by f0restgump92** [comment]
Official mysql image already has this feature. 
Take a look at [this](https://github.com/docker-library/mysql/blob/master/8.0/docker-entrypoint.sh)

**Comment by jaschaio** [comment]
Would love to see this too

**Comment by tompizmor** [comment]
As I commented in the PR, we are interested in this featur, and as you mention is worth it to add it to all containers. 
However, we will need to delay the work on this until we have more capacity. 

In any case, if any of you requires this feature, you can fork the repo and build your custom docker image applying similar changes to [this PR](https://github.com/bitnami/bitnami-docker-mariadb/pull/141)

**Comment by AquaeAtrae** [comment]
bump

@tompizmor Any update on this? Maybe just for a few popular containers like wordpress ([official getenv_docker here](https://github.com/docker-library/wordpress/blob/master/wp-config-docker.php#L26)) and mariadb (PR above)?

**Comment by juan131** [comment]
Hi everyone,

There is an internal task associated to this issue, but we did not find time to work on it due to our priorities.

Please note we highly recommend using Kubernetes to run containers on production. Our containers are compatible with Docker Swarm, however, adding support for advanced features available in this platforms is not in our roadmap at this very moment.

**Comment by 3rd3** [comment]
@juan131 Hello Juan. Could you kindly recommend a tutorial, example project or other resource detailing how to securely pass credentials to Bitnami images both in a development and production environment? I guess you are referring to Kubernetes Secrets? Wouldn't the problem remain that root passwords are passed as environment variables that can be retrieved with `docker inspect`? Thanks.

**Comment by rafariossaa** [comment]
Hi, 
  This image is mostly used in [this mysql chart](https://github.com/bitnami/charts/tree/master/bitnami/mysql) where that use case is solved by using secrets.
  Nevertheless,  you can use mysql's environment variable: `MYSQL_ROOT_PASSWORD_FILE` pointing to a file that contains the password. To use it, you will need to provide and mount that file to the container and configure the environment variable accordingly.

**Comment by carrodher** [comment]
Unfortunately, I will close this Issue because after reviewing this topic, it was not done in the past nor there are plans to work on it in the short-mid term.

Being side that, since this project is publicly available, would you like to contribute by creating a PR implementing this feature? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
