### ISSUE TITLE
replication_do_table not working.

### ISSUE THREAD

**Issue by Internetabi** [bitnami/bitnami-docker-mysql#48]
hello only_table replication not working help me please.

**Comment by carrodher** [comment]
Could you please provide us a little more information filling the following template?

**Description**
```
Briefly describe the problem you are having in a few paragraphs.
```
**Steps to reproduce the issue:**
```
1. [First Step]
2. [Second Step]
3. [and so on...]
```
**Describe the results you received:**
```
What actually happens
```
**Describe the results you expected:**
```
What you expect to happen 
```
**Additional information you deem important (e.g. issue happens only occasionally):**
```
Any additional information, configuration or data that might be necessary to reproduce the issue.
```
**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
