### ISSUE TITLE
Where is mysql version 5.7.21 tag and images? 

### ISSUE THREAD

**Issue by inix** [bitnami/bitnami-docker-mysql#56]
I examined mysql version in bitnami/mysql [docker image repo](https://github.com/bitnami/bitnami-docker-mysql),there is no mysql version 5.7.21,this version have deployed in our production environment,but version 5.7.21 do not reside in bitnami's repo.

How can I use 5.7.21 version image or can I just replace docker hub official mysql image in values.yaml?

**Comment by rafariossaa** [comment]
Hi @inix,
  The current version of our mysql charts is 5.7.24 but, as you said, you can point the image to bitnami/mysql:5.7.21 get that release.

Best regards,
Rafael Rios

**Comment by inix** [comment]
@rafariossaa 
Ok,Thanks.
This helps a lot!
