### ISSUE TITLE
Add ability to connect to the database over SSL

### ISSUE THREAD

**Issue by pentago** [bitnami/bitnami-docker-mysql#57]
**Feature Request**

One should be able to configure and connect to the database over SSL. 
Scripts could either generate required assets (crt,key,ca) or it can be left up to user with clear instructions.
This is of the utmost and critical importance for public-facing services like remote MySQL server.

Is it possible to add this request to the backlog?
Thanks in advance!

**Comment by juan131** [comment]
Hi @pentago 

Thanks for your suggestion, I agree it's a feature we should make easier to support.

There's already a task in the backlog to work on this feature. Other users requested it for Matomo, see https://github.com/bitnami/bitnami-docker-matomo/issues/21

I'll try to raise the priority of this task so we can work on this feature sooner.
