### ISSUE TITLE
[Question] How to use old mysql version 5.7.21 with latest debian 9 docker build?

### ISSUE THREAD

**Issue by inix** [bitnami/bitnami-docker-mysql#58]
**Description**

Our production deployed Oracle mysql version 5.7.21,but the old Bitnami mysql docker image '5.7.21-r13' do not compatible with latest helm chart version.
I want to build mysql version 5.7.21 with latest debian 9 docker file manually ,but I have no idea to find package name of corresponding docker file from Bitnami website.

**Describe the results you received:**

I can download mysql 5.7.21 file: 
`https://downloads.bitnami.com/files/stacksmith/mysql-5.7.21-9-linux-x64-debian-8.tar.gz`

**Describe the results you expected:**

Which mysql 5.7.21 file that I can build with debian 9 docker file?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@RqKubeDev06 ~/soft]docker info
Containers: 64
 Running: 45
 Paused: 0
 Stopped: 19
Images: 177
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.124GiB
Name: RqKubeDev06
ID: KVN2:33WL:JBGH:56JG:5FA4:T5SN:MBDU:U4IU:X64D:5FH7:T7CR:77MN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Live Restore Enabled: false

```

**Comment by juan131** [comment]
Hi @inix 

Please follow the steps below to do so:

- Clone this repository
- Open the directory **5.7/debian-9**
- Modify the Dockerfile so it looks like the one below:

```
FROM bitnami/minideb-extras-base:stretch-r63
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
    HOME="/" \
    OS_ARCH="x64" \
    OS_FLAVOUR="debian-8" \
    OS_NAME="linux"

# Install required system packages and dependencies
RUN install_packages libaio1 libatomic1 libc6 libgcc1 libncurses5 libsasl2-2 libstdc++6 libtinfo5 zlib1g
RUN . ./libcomponent.sh && component_unpack "mysql" "5.7.21-9"

COPY rootfs /
RUN /prepare.sh
ENV ALLOW_EMPTY_PASSWORD="no" \
    BITNAMI_APP_NAME="mysql" \
    BITNAMI_IMAGE_VERSION="5.7.24-debian-9-r13" \
    MYSQL_DATABASE="" \
    MYSQL_MASTER_HOST="" \
    MYSQL_MASTER_PORT_NUMBER="" \
    MYSQL_MASTER_ROOT_PASSWORD="" \
    MYSQL_MASTER_ROOT_USER="" \
    MYSQL_PASSWORD="" \
    MYSQL_PORT_NUMBER="3306" \
    MYSQL_REPLICATION_MODE="" \
    MYSQL_REPLICATION_PASSWORD="" \
    MYSQL_REPLICATION_USER="" \
    MYSQL_ROOT_PASSWORD="" \
    MYSQL_ROOT_USER="root" \
    MYSQL_USER="" \
    PATH="/opt/bitnami/mysql/bin:/opt/bitnami/mysql/sbin:$PATH"

EXPOSE 3306

USER 1001
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/run.sh" ]
```

- Build the image:

```
$ docker build . -t bitnami/mysql:5.7.21
```

**Comment by inix** [comment]
Hi @juan131 
I can download the correct file with your code.
I download both version 5.7.21-9(`mysql-5.7.21-9-linux-x64-debian-8`) and 5.7.24-1(`mysql-5.7.24-1-linux-amd64-debian-9`) mysql files,extract them and diff two folders,I found some 
 Bitnami base javascript files differences between two folder,there are some minor difference such as logs,but most are same.
I also examine those docker bash codes,but I have no idea what these files mean for.
My Question: do these js files impact docker image,such as system environment variables? If so,do I need replace mysql under files folder under 5.7.24-1 folder and package again?

See:
![mysqlver diff](https://user-images.githubusercontent.com/2264291/48041150-e78ee800-e1b6-11e8-942c-166afe5e5e63.png)

**Comment by juan131** [comment]
Hi @inix 

> do these js files impact docker image,such as system environment variables? If so, do I need replace mysql under files folder under 5.7.24-1 folder and package again?

Those Javascript files are part of the Nami module (which is not used anymore on containers) which was used to initialised the services on the container. As I mentioned, they're not used on containers (they're used on other platforms) and there'll be Bash scripts that'll do the equivalent. Therefore, you can ignore them.

**Comment by inix** [comment]
@juan131 
I see.Thanks for your explanation. I will build docker images manually from previous tar.gz files.
Thanks you!
