### ISSUE TITLE
Container does not start on Windows 10 Home (using Docker Toolbox)

### ISSUE THREAD

**Issue by klausroffe** [bitnami/bitnami-docker-mysql#59]
**Description**

I'm on Windows 10 Home and using Docker Toolbox. I cannot run the container with a volume mounted to host. Without mounted volume the container runs normally.

**Host info**

- OS Name: Microsoft Windows 10 Home Single Language
- OS Version: 10.0.17763 Build 17763
- OS Manufacturer: Microsoft Corporation		
- System Type: x64-based PC		
- Processor(s): Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz, 2401 Mhz, cores: 2
- Windows	Directory: C:\WINDOWS	
- System Directory: C:\WINDOWS\system32	
- Boot Device: \Device\HarddiskVolume4	
- Total Physical Memory (RAM): 15,9 Gb	
- Available Physical Memory: 7,12 Gb	
- Virtual Memory: Max Size: 32,9 Gb	
- Virtual Memory: Available: 20,5 Gb	
- Page File Size: 17,0 Gb
- Page File Location(s): C:\pagefile.sys

**Command to run container**

```
docker run -d --name mysql -e ALLOW_EMPTY_PASSWORD=yes -v //c/Users/admin/mysql:/bitnami/mysql/data --network mysql bitnami/mysql:latest
```

**Container output**

```
Welcome to the Bitnami mysql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MySQL setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing mysql database...
INFO  ==> Stopping mysql...
```

**Docker Version**

Client:
-  Version:       18.03.0-ce
-  API version:   1.37
-  Go version:    go1.9.4
-  Git commit:    0520e24302
-  Built: Fri Mar 23 08:31:36 2018
-  OS/Arch:       windows/amd64
-  Experimental:  false
-  Orchestrator:  swarm

Server: Docker Engine - Community
 
- Engine:
- Version:      18.09.0
- API version:  1.39 (minimum version 1.12)
- Go version:   go1.10.4
- Git commit:   4d60db4
- Built:        Wed Nov  7 00:52:55 2018
- OS/Arch:      linux/amd64
- Experimental: false

**Docker Info**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: rfmiiyk5cpf0xq79v9vptr6yt
 Is Manager: true
 ClusterID: z7fc1mgkwbzxv2xz0wswk3eue
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.0.2.15
 Manager Addresses:
  10.0.2.15:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.79-boot2docker
Operating System: Boot2Docker 18.09.0 (TCL 8.2.1)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.4MiB
Name: default
ID: COY3:ZY2R:D5QU:XVWQ:CEP6:L6EA:SVWI:MRR5:MKCP:VH76:JMJO:XWQE
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by juan131** [comment]
The error you faced means that your filesystem doesn't support [aio](http://lse.sourceforge.net/io/aio.html):

```
File ./ib_logfile101: 'aio write' returned OS error 122. Cannot continue operation
```

More info: https://stackoverflow.com/questions/19265916/file-ib-logfile101-aio-write-returned-os-error-122

You can fix it by adding the line below to the configuration file:

```
innodb_use_native_aio=0
```

Here you can find information about how to use a custom configuration file:
https://github.com/bitnami/bitnami-docker-mysql#configuration-file

**Comment by klausroffe** [comment]
I don't belive, it worked for me with my_custom.cnf!
Many thanks guys!!!

Previously I've tried to edit my.cnf file using `docker cp` command but it didn`t work. Why?

**Comment by juan131** [comment]
> I don't belive, it worked for me with my_custom.cnf!

That's great! Glad to hear that.

> Previously I've tried to edit my.cnf file using docker cp command but it didn`t work. Why?

I'm not sure.. Lack of permissions? Could you share the exact command you used?

**Comment by klausroffe** [comment]
I was trying something like

`docker run -d --name tst -e ALLOW_EMPTY_PASSWORD="yes" -e BITNAMI_DEBUG="true" -v //c/Users/admin/tst:/bitnami/mysql/data bitnami/mysql:latest`

Then `docker cp tst:/opt/bitnami/mysql/conf/my.cnf c:/tst`, adding a line `innodb_use_native_aio=0` under `[mysqld]` section and then copying it back to container `docker cp c:/tst/my.cnf tst:/opt/bitnami/mysql`

And when starting the container I faced with `InnoDB: File ./ib_logfile101: 'aio write' returned OS error 122` error.

**Comment by klausroffe** [comment]
I was copying my.cnf back to `/opt/bitnami/mysql` not to `/opt/bitnami/mysql/conf` that was the error!
With the right path it worked for me, too.
Thank you again @juan131 !

**Comment by juan131** [comment]
Great!!! I'm glad you could solved the issue copying the file to the right path 😃
