### ISSUE TITLE
How to turn off ONLY_FULL_GROUP_BY?

### ISSUE THREAD

**Issue by marknguyen85** [bitnami/bitnami-docker-mysql#66]
Hi there.

when i ran select statement with group and  got error
`Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column ‘db.table.col’ which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

plz help me how to turn off ONLY_FULL_GROUP_BY?

**Comment by rafariossaa** [comment]
Hi @marknguyen85,
   You can disable ONLY_FULL_GROUP_BY using:

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

 Anyway, I would review the select you are trying to run and make sure you really need to disable this option.

Best regards,
Rafael Rios Saavedra

**Comment by marknguyen85** [comment]
I want to apply it to all users and any select statement so I think your hint command only applies to one select after that.
i found setting in the custom config 
```
[mysqld]  
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```
then i create custom file according to instructions #Configuration file

> Configuration file
The image looks for user-defined configurations in /opt/bitnami/mysql/conf/my_custom.cnf. Create a file named my_custom.cnf and mount it at /opt/bitnami/mysql/conf/my_custom.cnf.
>..........................

but i could not start docker

**Comment by rafariossaa** [comment]
Hi @marknguyen85,
  This is what I did:

  Create a file `/home/user/test/my_custom.cnf` with the following content:

```
[mysqld]  
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```
If you are using windows when creating the file, save the file using linux `end of line` format.

Run the container with the following command:
```
docker run --name mysql \
 -p 4306:3306 \
 -e ALLOW_EMPTY_PASSWORD=yes \
 -e MYSQL_USER=my_user \
 -e MYSQL_PASSWORD=my_password \
 -e MYSQL_DATABASE=my_database \
 -v /home/user/test/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf \
 bitnami/mysql:latest
```
```
INFO  ==> ** Starting MySQL setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing mysql database...
INFO  ==> Stopping mysql...
INFO  ==> ** MySQL setup finished! **

INFO  ==> ** Starting MySQL **
2019-03-11T08:02:52.285401Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
...
2019-03-11T08:07:29.620586Z 0 [Note] /opt/bitnami/mysql/bin/mysqld: ready for connections.
Version: '5.7.25'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  MySQL Community Server (GPL)
```
Check the option has been disabled:
```
$ mysql -P4306 -u my_user -pmy_password -h 127.0.0.1 my_database -e "show variables like 'sql_mode'"
mysql: [Warning] Using a password on the command line interface can be insecure.
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                     |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+

```

Note: I use port 4403 because in my computer I have another mysql running.

**Comment by marknguyen85** [comment]
thanks rafariossaa

**Comment by mbaric** [comment]
Solution without changing `docker-compose.yml`

I've tried and succeeded to turn off _ONLY_FULL_GROUP_BY_ with those two commands, of course you can concatenate it to one but I like being diligent and see what's happening through the steps: 

Few notes:

- variable `herePutTheFullNameOfYourServiceContainer` in the example below will name it _comany_db1_
- Make sure you are connecting to your docker DB container with `root` user

```
db_id=$(docker ps -f name=_comany_db1_ --format "{{.ID}}")
docker exec $db_id mysql -hdb -uroot -ppass1 mydatabase -e "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
```

Let me know if you need more help with it I'll try to help, as usual :). Thanks.

**Comment by rafariossaa** [comment]
Hi @mbaric ,
  Thanks for providing other solution to this issue.

Best regards,

**Comment by laratuto** [comment]
[Solved ](https://laratuto.com/solved-how-do-i-disable-only_full_group_by-in-mysql/)

**Comment by laratuto** [comment]
[Solution is below](https://laratuto.com/solved-how-do-i-disable-only_full_group_by-in-mysql/)
