### ISSUE TITLE
Master Failover and Recovery from Slave in Docker Swarm.

### ISSUE THREAD

**Issue by G-K-Patel** [bitnami/bitnami-docker-mysql#68]
Hi Bitnami Image Team, 

I really like you Images, they are light and easy to use. Currently, I am trying to use your MySQL image in docker swarm. The swarm works very fluently, only when one of the slaves fails. But, I wanted to know, **what to do when a Master fails. How can I promote an existing Slave to Master?** 

Thank you for you help, I very much appreciate it.

**Comment by ba-andreas** [comment]
Hello,

i have tried the solution with the promotion of the slave explained in the mysql documentation.
My problem is now that it still doesn't work because even after promoting the slave to a master it is still in read-only mode.
I think its due to the DB_EXTRAS_FLAG variable in the libmysql.sh used for initializing the slave container. 
Thank you for your help.

Best regards Andreas Baumeister

**Comment by miguelaeh** [comment]
Hi @ba-andreas ,
Did you configure the `MYSQL_ROOT_PASSWORD` environment variable?

**Comment by ba-andreas** [comment]
Yeah i configured the environment variable for the root password.
I also found a solution to my previous question, I simply had to execute the "set Global read_only = false" command on the slave node.

So I executed the following commands on the slave:
- Set Global read_only = false;
- Stop slave
- Reset master

Are these all the steps required to promote the slave node to a master node? Or are there other configurations/flags which can prevent the usage of a promoted slave container as a master for a longer time? Especially, in the context of adding a new "empty" slave to the "promoted" slave node.

Thank you for your previous answer and help.

Best regards Andreas Baumeister

**Comment by miguelaeh** [comment]
Hi,
as @rafariossaa posted, the steps to promote a slave to master are the the steps on the MySQL docs.

>Or are there other configurations/flags which can prevent the usage of a promoted slave container as a master for a longer time?

Not sure about that, once you promote a salve to master, it will become the master, it changes his role and it is no longer a slave unless you change manually again.
