### ISSUE TITLE
Container exits with permission denied writing to mysqld.log

### ISSUE THREAD

**Issue by kkuphal** [bitnami/bitnami-docker-mysql#70]
**Description**

Running bitnami mysql container on VMware integrated containers exist with permission denied writing to mysqld.log (which is symlinked to /dev/stdout)

**Steps to reproduce the issue:**

1. docker run -e ALLOW_EMPTY_PASSWORD=yes bitnami/mysql:latest

**Describe the results you received:**

Welcome to the Bitnami mysql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MySQL setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing mysql database...
INFO  ==> Stopping mysql...
INFO  ==> Stopping mysql...
INFO  ==> ** MySQL setup finished! **

INFO  ==> ** Starting MySQL **
2019-06-12T20:16:32.357029Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.16) starting as process 249
2019-06-12T20:16:32.360230Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2019-06-12T20:16:32.360243Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2019-06-12T20:16:32.361248Z 0 [ERROR] [MY-010187] [Server] Could not open file '/opt/bitnami/mysql/logs/mysqld.log' for error logging: Permission denied
2019-06-12T20:16:32.363560Z 0 [ERROR] [MY-010119] [Server] Aborting
2019-06-12T20:16:32.364229Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.16)  Source distribution.

**Describe the results you expected:**

Successful startup

Does not occur with bitnami/mysql:5.7.21-r6 (root enabled version)

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.0-ce
 API version:       1.25 (downgraded from 1.38)
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          1.5.2
  API version:      1.25 (minimum version 1.19)
  Go version:       go1.8.6
  Git commit:       30b67a14
  Built:            Thu Mar 14 09:33:31 2019
  OS/Arch:          linux/amd64
  Experimental:     true

```

- Output of `docker info`:

```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 20
Server Version: v1.5.2-20879-30b67a14
Storage Driver: vSphere Integrated Containers v1.5.2-20879-30b67a14 Backend Engine
VolumeStores: default
vSphere Integrated Containers v1.5.2-20879-30b67a14 Backend Engine: RUNNING
 VCH CPU limit: 161904 MHz
 VCH memory limit: 1.274 TiB
 VCH CPU usage: 26793 MHz
 VCH memory usage: 539.2 GiB
 VCH storage usage: 104.1 GiB
 VCH images storage usage: 7.621 GiB
 VCH containers storage usage: 96.51 GiB
 VMware Product: VMware vCenter Server
 VMware OS: linux-x64
 VMware OS version: 6.5.0
 Registry Whitelist Mode: disabled.  All registry access allowed.
Plugins:
 Volume: vsphere
 Network: bridge vic-container-network
 Log:
Swarm: inactive
Operating System: linux-x64
OSType: linux-x64
Architecture: x86_64
CPUs: 161904
Total Memory: 1.274TiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: registry-1.docker.io
Experimental: false
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

VMware integrated containers v1.5.2-7206
Storage volume is NFS mounted (does require chown for non-root permissions for mounted data.  Should not apply to mysqld.log mapped to stdout)

**Comment by rafariossaa** [comment]
Hi @kkuphal,
  I was not able to reproduce it on my docker locally, Could you try to run it as a root container with this command:

`docker run -u root -e ALLOW_EMPTY_PASSWORD=yes bitnami/mysql:latest`

Maybe it is something related with that platform.

**Comment by kkuphal** [comment]
Different behavior but it doesn't seem to complete the initalization

```
Welcome to the Bitnami mysql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MySQL setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing mysql database...
mysql:x:1000:
```

**Comment by rafariossaa** [comment]
Hi @kkuphal ,
  Finally , I was able to reproduce it. I'm trying to figure out the problem and a fix.

**Comment by rafariossaa** [comment]
Hi @kkuphal ,
  Could your try to run an older release of the 8.0.16 ?
```
docker run -e ALLOW_EMPTY_PASSWORD=yes bitnami/mysql:8.0.16-r0
```
and 
```
docker run -u root  -e ALLOW_EMPTY_PASSWORD=yes bitnami/mysql:8.0.16-r0
```

**Comment by parulraheja98** [comment]
Hi @rafariossaa Changing the version to mysql:8.0.16 fixed my problem , I was having the same issue.
Thanks a lot :+1:

**Comment by rafariossaa** [comment]
Thanks @parulraheja98 , let's see if @kkuphal  can use this as workaround meanwhile we fix the issue properly.

**Comment by rafariossaa** [comment]
Hi @kkuphal, 
  This should be already fixed, could you try again ? Please, remove the previous mysql:latest image to make sure you are downloading the latest release of the 8.0.16.

Best regards,

**Comment by navndn** [comment]
Hi @rafariossaa 
Is this issue fixed already? I'm still getting the error for :5.7 and :latest versions

**Comment by rafariossaa** [comment]
Hi @navndn 
  Which command are you using ?
  I can run 5.7 with: 
`docker run -u root -e ALLOW_EMPTY_PASSWORD=yes bitnami/mysql:5.7-debian-9`
  and latest with: 
`docker run --name mysql   -e ALLOW_EMPTY_PASSWORD=yes  bitnami/mysql`.

Could you provide also the platform and docker version you are using ?

**Comment by navndn** [comment]
@rafariossaa , Here it is
```
navndn$ docker run -u root -e ALLOW_EMPTY_PASSWORD=yes bitnami/mysql:5.7-debian-9

Welcome to the Bitnami mysql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MySQL setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing mysql database...
INFO  ==> Stopping mysql...
INFO  ==> Stopping mysql...
INFO  ==> ** MySQL setup finished! **

INFO  ==> ** Starting MySQL **
2019-08-20T07:22:09.812583Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
2019-08-20T07:22:09.812680Z 0 [Note] /opt/bitnami/mysql/bin/mysqld (mysqld 5.7.27) starting as process 1 ...
2019-08-20T07:22:09.815094Z 0 [ERROR] Could not open file '/opt/bitnami/mysql/logs/mysqld.log' for error logging: Permission denied
2019-08-20T07:22:09.815125Z 0 [ERROR] Aborting

2019-08-20T07:22:09.815149Z 0 [Note] Binlog end
2019-08-20T07:22:09.816436Z 0 [Note] /opt/bitnami/mysql/bin/mysqld: Shutdown complete
```

```
navndn$ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```

navndn$ lsb_release -d
Description:    Ubuntu 19.04
```



Btw, this problem goes away if I mount a host volume to logs directory like this(as root user)  `./data/mysql_logs:/opt/bitnami/mysql/logs`

**Comment by rafariossaa** [comment]
Hi @navndn ,
  The problem is when the `-u root` parameter is used. 
  Sorry, I didn't noticed that detail before. We are interested in this use case, is running the container as root necessary for you? why ?.

**Comment by navndn** [comment]
@rafariossaa, sorry I missed your comment.. My general docker experience so far is in dev/test environment, by default, have mostly used containers as root user. When I started trying out bitnami containers as non-root, mounting docker-volumes from host machine resulted in permission errors, so I added `-u root`. This might be an ignorant question, how to mount docker-volumes from host machine as non-root ? I do want to avoid root ..
Thanks

**Comment by javsalgar** [comment]
Hi.

Just a quick note to let you know that we released a new version of the container (r39) that fixes the issue. 

https://github.com/bitnami/bitnami-docker-mysql/commit/33e8ebcc32ae1c45e4e9f4264889e93e53aaabba

Could you confirm that it now works for you?

**Comment by navndn** [comment]
Hi, @javsalgar, r39 is working fine for me. Thanks

**Comment by vishakha-lall** [comment]
I get the same error when I try the deployment on Kubernetes. Weird part is, the same image works with `docker-compose.yml` as desired. Any pointers?

I am using version `5.7`

**Comment by rafariossaa** [comment]
Hi @vikram-bitnami ,
  This issue was closed, some releases happened since this issue was closed so maybe it is another kind of issue.
 Do you mind to open a new one so we can follow you issue there ?

Thanks forehand.

**Comment by vikram-bitnami** [comment]
@rafariossaa I think you pinged me in error as I am not a participant in this thread. Thank you.

**Comment by rafariossaa** [comment]
@vikram-bitnami , yes I am sorry, it was unintended.
