### ISSUE TITLE
How to healthcheck mysql container?

### ISSUE THREAD

**Issue by danepowell** [bitnami/bitnami-docker-mysql#73]
For downstream services such as Lando using this image, I'm wondering how we are supposed to reliably healthcheck that MySQL is running and stable.

The problem is that MySQL is actually started twice, first via setup.sh and then by run.sh. It's stopped momentarily in between. So if you use a standard MySQL healthcheck such as `mysql -uroot --silent --execute "SHOW DATABASES;"`, this might pass while setup.sh runs, but then when you try to make production calls to the database it might be down while run.sh runs.

I don't know how to construct a healthcheck that ensures that MySQL has been started for the second time (via run.sh) and will continue to stay up.

**Comment by andresbono** [comment]
Hi @danepowell, we can try to improve this behavior, any suggestions will be welcome.

In the meantime, can you try with a healthcheck that queries the database multiple times?

**Comment by danepowell** [comment]
I'm not sure how querying multiple times would help. We could simply add a delay but that still creates a race condition like we have today. I'd rather have a deterministic fix.

I don't fully understand why setup.sh stops MySQL only so it can be restarted moments later. If there's not a good reason for that, maybe fix that. That would also improve startup times.

Otherwise, I think the best solution is for bitnami-docker-mysql to set a flag once it's finished initializing the db. I'll open a PR for this.
