### ISSUE TITLE
Change the value of max_binlog_cache_size

### ISSUE THREAD

**Issue by hh-project-config** [bitnami/bitnami-docker-mysql#75]
Thanks for providing this useful container. 

I am doing a research aiming at finding issues in configuration files. I have a question about one MySQL config: `max_binlog_cache_size`. It seems the [official document](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_max_binlog_cache_size) says "The maximum recommended value is 4GB; this is due to the fact that MySQL currently cannot work with binary log positions greater than 4GB."

However, the default value is 18446744073709551615, which is much larger than the recommended value. 

Shall we change the value to 4GB? 
Thanks!

**Comment by carrodher** [comment]
Hi, we are not changing this value, it is using the default value, according to the [official documentation](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_max_binlog_cache_size), this default value is the one you commented.

If you need to change this value, you can use a custom configuration file, please take a look at the following README sections:
- https://github.com/bitnami/bitnami-docker-mysql#configuration-file
- https://github.com/bitnami/bitnami-docker-mysql#overwrite-the-main-configuration-file
