### ISSUE TITLE
Healthcheck should take into account slave syncronisation status.

### ISSUE THREAD

**Issue by matthewlilley** [bitnami/bitnami-docker-mysql#78]
Currently with a replication setup, and healtcheck based on an INITIALIZED file being touched, it's possible to connect to a slave before it's ready. I've found it's only safe to use the slave once Slave_IO_Running: Yes && Slave_SQL_Running: Yes && Seconds_Behind_Master: 0.

**Comment by andresbono** [comment]
Hi @matthewlilley, are you referring to this section of the README? [Ensuring the database is ready before connecting](https://github.com/bitnami/bitnami-docker-mysql#ensuring-the-database-is-ready-before-connecting).

Would you like to open a PR to make the section more complete explaining the replication scenario?
