### ISSUE TITLE
Question: why do slave need DB_MASTER_ROOT_USER?

### ISSUE THREAD

**Issue by zjuchenyuan** [bitnami/bitnami-docker-mysql#87]
**Description**

In your readme, you provide MYSQL_MASTER_ROOT_USER and MYSQL_MASTER_ROOT_PASSWORD enviroment value for setting up a slave instance.

But I find out the code just use it for `select 1`:

https://github.com/bitnami/bitnami-docker-mysql/blob/89fd8bfd0edcc776caf30dd2df20ed7477045a6d/8.0/debian-9/rootfs/libmysql.sh#L286-L288

**Describe the results you expected:**

I do not think that root priviledge is required for checking whether master is connectable.

Would you remove `MYSQL_MASTER_ROOT_USER` and `MYSQL_MASTER_ROOT_PASSWORD`? I think use existing `MYSQL_REPLICATION_USER` should be enough.

**Comment by juan131** [comment]
Hi @zjuchenyuan 

> I do not think that root privilege is required for checking whether master is connectable.

That's an interesting approach. I took a look to the initialisation scripts and it seems we're exclusively using these credentials to ensure master is reachable. If we can use different credentials to ensure the master node is reachable, then I'm okay with removing them.

Please feel free to do a PR and I'll be glad to review it.
