### ISSUE TITLE
Cannot deploy slave with service LoadBalancer

### ISSUE THREAD

**Issue by idkw** [bitnami/bitnami-docker-mysql#90]
I tried deploying the following helm chart https://hub.kubeapps.com/charts/bitnami/mysql
With default values it works well.
However if I try to set to following variables it doesn't work : 

```
service.type: LoadBalancer
service.loadBalancerIP: 10.132.8.0 (an internal static IP on my kub cluster)
```

It successfully creates the load balancer ressource on GCP platform for the master replica
However for the slave replica, the chart contains a bug because it uses the same loadBalancerIp value. This cannot be and thus triggers the following error on the slave service : 

```
Error syncing load balancer: failed to ensure load balancer: googleapi: Error 409: IP_IN_USE_BY_ANOTHER_RESOURCE - IP '10.132.8.0' is already being used by another resource.
```

My suggestion would be to provide two separate IP `loadBalancerIP.master` and `loadBalancerIP.slave` and assign them properly in the master and slave service template

Functionnaly it also makes no sense to load balance accross master and slave. Either you want to work with the master or with the slaves, not both without knowing which you connect to.

**Comment by dani8art** [comment]
Hi @idkw ,

You are right, I was able to reproduce it, also I open a PR on `bitnami/charts` that fix this issue. I will keep you updated.

Regards.

**Comment by dani8art** [comment]
Hi @idkw , the PR was merged, please use the new version of the chart `6.8.0`, it should work properly. 

Thank you so much for your feedback, do not hesitate to contact us again if you have any other problem.

Regards.
