### ISSUE TITLE
Execute .sh files in docker-entrypoint-initdb.d in Slave node

### ISSUE THREAD

**Issue by Funky911** [bitnami/bitnami-docker-mysql#91]
Maybe I'm wrong, but the .sh files that I place in /files within my chart directory don't get executed on the slave node start, only in master. How could I make any .sh files to get executed during the slave initialization? 

Thanks!

**Comment by rafariossaa** [comment]
Hi @Funky911, 
  I am sorry, it is not possible. The files are only mounted on the master node.
