### ISSUE TITLE
Lots of warnings on slave from exporter.go

### ISSUE THREAD

**Issue by idkw** [bitnami/bitnami-docker-mysql#92]
I updated my deployment to https://hub.kubeapps.com/charts/bitnami/mysql version 6.9.0

With default settings and replication enabled, I see a lot of warnings on the slave : 

```
2020-02-20 17:14:12.657 CET
time="2020-02-20T16:14:12Z" level=error msg="Error pinging mysqld: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: NO)" source="exporter.go:146"
```

I am however able to connect myself to both the master and the slave with the root username and password I configured by passing the chart value `root.password`. So it must be the `exporter.go` script that is somehow misconfigured.

Beside that, the slave replication process works correctly.

Feel free to ask me more information if you need to. I'm not really sure what else to look for.

**Comment by andresbono** [comment]
Thanks for filling this issue, @idkw. We are going to investigate it and we will try to reproduce the issue on our side.

**Comment by andresbono** [comment]
Hi @idkw, we couldn't reproduce your issue yet. The errors we can see are transient, and once the database cluster is up and running, the errors doesn't appear anymore.

Can you double check that the value of the environment variable for the password is correct?

```
kubectl exec -ti mysql-slave-0 -c metrics -- bash -c 'env | grep MYSQL_MASTER_ROOT_PASSWORD'
```

Can you think of any peculiarity of your deployment that can be causing your issue?
