### ISSUE TITLE
mysql: [ERROR] unknown variable 'max_connections=1000'

### ISSUE THREAD

**Issue by standup-jb** [bitnami/bitnami-docker-mysql#95]
I use the helm deploy mysql cluster. the default mysql max_connections = 150 . but it is too small for our business . so I want to set max_connections = 1000 when the mysql start . I meet the error . 

I modify the my.cnf as below
```
  config: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    max_connections=1000
    max_user_connections=500
```

The error log as below 
```
mysql 09:05:15.27
mysql 09:05:15.27 Welcome to the Bitnami mysql container
mysql 09:05:15.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 09:05:15.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 09:05:15.28 Send us your feedback at containers@bitnami.com
mysql 09:05:15.28
mysql 09:05:15.29 INFO  ==> ** Starting MySQL setup **
mysql 09:05:15.38 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 09:05:15.38 INFO  ==> Initializing mysql database
mysql 09:05:15.41 INFO  ==> Using persisted data
mysql: [ERROR] unknown variable 'max_connections=1000'
/opt/bitnami/scripts/libmysql.sh: line 518: ver_split[2]: unbound variable
/opt/bitnami/scripts/libversion.sh: line 20: 1: version is required
```
I am from China , English is not my mother language .  If there has some description is not clearly. 
I am very sorry.

**Comment by Mauraza** [comment]
Hi @standup-jb, 

Could you tell me with the tag of the image are you using? because I using `tag: 8.0.19-debian-10-r64` I don't be able to reproduce it. 
I used `helm install my-release -f values.yaml bitnami/mysql` with your values of `max_connections=1000` and `max_user_connections=500`

**Comment by standup-jb** [comment]
> Hi @standup-jb,
> 
> Could you tell me with the tag of the image are you using? because I using `tag: 8.0.19-debian-10-r64` I don't be able to reproduce it.
> I used `helm install my-release -f values.yaml bitnami/mysql` with your values of `max_connections=1000` and `max_user_connections=500`

I Use the mysql tag as below . You can use this version try it again . 

image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 5.7

**Comment by Mauraza** [comment]
Hi @standup-jb, 

I didn't be able to reproduce, Could you tell me how are you deploy the chart of MySQL?

**Comment by standup-jb** [comment]
> Hi @standup-jb,
> 
> I didn't be able to reproduce, Could you tell me how are you deploy the chart of MySQL?

I use the helm deploy the mysql-cluster in k8s . The helm repository is https://developer.aliyun.com/hub/detail?spm=a2c6h.12873679.0.0.7ecf1ae5cORF8M&name=mysql&version=6.8.0#/?_k=uz4x39 。
I modified the values-production.yaml . add the max_connections .

**Comment by Mauraza** [comment]
Could you use our helm chats?, only have to follow the instruction here [https://github.com/bitnami/charts](https://github.com/bitnami/charts). In this chart, it's working correctly.
I hope that helps you.

**Comment by standup-jb** [comment]
> Could you use our helm chats?, only have to follow the instruction here https://github.com/bitnami/charts. In this chart, it's working correctly.
> I hope that helps you.

OK，Use the  AliCloud product is more easily in China . Thanks for you helping . I will try your helm charts when I have some rest time . If your product don't have this issue. I will close this issue .
